[project]
name = "object_recognition"
version = "0.1.0"
description = "A robot ball path planning system"
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["."]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"